Ansible 4
otus-devops-2019-05/chirkovsergey_infra pull request #15
Opened 2019-07-31 11:13 UTC by chirkovsergey

# Выполнено ДЗ № 11

 - [x] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:

 - Пункт 1
   Локально при помощи Vagrant & ansible создали вм и установили на них приложение 
 - Пункт 2
   Используя Molecule и Testinfra  создали тест  роли DB 
 - Пункт 3
   Сборкак образа Packerom теперь использует роли Ansible  
 - Пункт 4
   --- 
## Как запустить проект:

## Как проверить работоспособность:

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-07-31 16:59 UTC, AlexeyKondratyev requested changes
Добрый день!
Спасибо за работу!
Попробуйте поднять вагрантом вм, должна появиться ошибка /usr/bin/python: not found.
Попробуйте разобраться почему.

2019-08-01 10:49 UTC, chirkovsergey commented
Добрый день. 
Ошибка / usr / bin / python: не найдена. 
Попробуйте разобраться почему.
это вопрос общего характера? или действительно должна быть ошибка при попытки развернуть вм при помощи вагранта? 
просто я несколько раз проверял и сборка проходит без ошибок, приложение доступно.

2019-08-01 14:17 UTC, AlexeyKondratyev approved these changes

2019-08-01 14:19 UTC, AlexeyKondratyev commented
Не, не общий. 
Вообще не должно.
Если запускали и вагрант с провижионером корректно отрабатывает то работа принята!

2019-08-02 07:21 UTC, merged